name: Dependabot Auto-Merge

# Dependabot Pull Requests Auto-Merge

# The auto-merge will be performed only if the semantic version for the changes is MINOR or PATCH.
# Pull Requests with semantic versions MAJOR will need manual review and approval.

on:
  workflow_run:
    workflows: ["Build & Report"]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-automerge:
    runs-on: ubuntu-latest
    # CONDICIONES DE SEGURIDAD:
    # 1. El workflow de Java debe haber terminado en 'success' (Verde)
    # 2. El actor que disparó el evento original debe ser Dependabot
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.actor.login == 'dependabot[bot]'

    steps:
      # Necesitamos hacer checkout para leer la metadata de dependabot
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Obtain Dependabot Metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Merge
        if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-minor' || steps.metadata.outputs.update-type == 'version-update:semver-patch' }}
        run: gh pr merge --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.workflow_run.pull_requests[0].html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
